config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # root 'males#index'

  resources :males
end


#    Prefix Verb   URI Pattern               Controller#Action
#   welcome GET    /welcome(.:format)        males#index
#     males GET    /males(.:format)          males#index
#           POST   /males(.:format)          males#create
#  new_male GET    /males/new(.:format)      males#new
# edit_male GET    /males/:id/edit(.:format) males#edit
#      male GET    /males/:id(.:format)      males#show
#           PATCH  /males/:id(.:format)      males#update
#           PUT    /males/:id(.:format)      males#update
#           DELETE /males/:id(.:format)      males#destroy

app/models/male.rb
class Male < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/males_controller.rb
class MalesController < ApplicationController

	def index
		@males = Male.all

	end

	def new
		render :new	
	end

	def create
		@male = Male.new(params.require(:male).permit(:shirt, :pant))
		@male.save

		redirect_to @male
	end

	def show
		male_id = params[:id]
		@male = Male.find(male_id)
		render :show	
	end

	def edit
	    male_id = params[:id]
	    @male = Male.find(male_id)
  	end

	def update
		male_id = params[:id]
		@male = Male.find(male_id)
		male_params = params.require(:male).permit(:shirt, :pant)
		@male.update_attributes(male_params)
		render :show
	end
	
	def destroy
		male_id = params[:id]
		male = Male.find(male_id)
		male.destroy

		redirect_to males_path	
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/males_helper.rb
module MalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/Males/edit.html.erb
 <%= form_for @male, url:{action:"update"} do |f| %>
  <p>
    <%= f.label :shirt %><br>
    <%= f.text_field :shirt %>
  </p>
 
  <p>
    <%= f.label :pant %><br>
    <%= f.text_area :pant %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/Males/index.html.erb
<% @males.each do |male| %>

  <div>Shirt: <%= male.shirt %></div>
  <div>Pant: <%= male.pant %></div>
  <div>
  <%= button_to 'show', male_path(male), method: :get %>
  <%= button_to 'edit', edit_male_path(male), method: :get %>
  <%= button_to 'delete', male_path(male),
            method: :delete,
            data: {confirm: "are you sure?"} %>
</div>
<% end %>

app/views/Males/new.html.erb
 <%= form_for :male, url:{action:"create"} do |f| %>
  <p>
    <%= f.label :shirt %><br>
    <%= f.text_field :shirt %>
  </p>
 
  <p>
    <%= f.label :pant %><br>
    <%= f.text_area :pant %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/Males/show.html.erb
<div><%= @male.shirt %></div>
<div><%= @male.pant %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokey</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="jumbotron">
  <div class="container">
    
  </div>
</div>
<div class="container-fluid">
 



<%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>